### PR TITLE
@PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by ivankravets**
* This library in Web Registry: http://platformio.org/#!/lib/show/440/Thread
* Specification: [PlatformIO Library Manager](http://docs.platformio.org/en/latest/librarymanager/index.html)
* Integration: [IDE Integration](http://docs.platformio.org/en/latest/ide.html)

### CODE REVIEW

**Comment by ivanseidel** [comment]
Really Interesting! I didn't know Platformio...
Would you like to implement this to the other libraries?
+ https://github.com/ivanseidel/Gaussian
+ https://github.com/ivanseidel/DueTimer
+ https://github.com/ivanseidel/LinkedList

Thanks

**Comment by ivankravets** [comment]
> Really Interesting! I didn't know PlatformIO...

Have you tried it already?

> Would you like to implement this to the other libraries?

Done! See http://platformio.org/#!/lib/search?query=author%253A%2522Ivan%20Seidel%2522

**Comment by ivanseidel** [comment]
Not yet, but will do it soon!

One thing that I have just noticed, is that the name on PlatformIO is using "Thread", not "ArduinoThread". That might confuse people if they already know ArduinoThread for some reason, what do you think?

**Comment by ivankravets** [comment]
> One thing that I have just noticed, is that the name on PlatformIO is using "Thread", not "ArduinoThread". That might confuse people if they already know ArduinoThread for some reason, what do you think?

See "Compatibility" section in http://platformio.org/#!/lib/show/440/Thread

P.S: We should avoid these trademarks in names. Arduino is TM and can't be used in Project/LIb names. However, it can be used with "for context". Like, "Thread for Arduino". See https://www.arduino.cc/en/Trademark/HomePage?from=Main.Trademark

This isn't my requirement, I don't have time for problems with Arduino owners. 

P.S.S. Yes, I know that hundreds libs in Internet use that "arduino" prefix and don't have any problems. It because "someone" from _ABOVE_ won't to contact with hundreds developers for single lib. 

Nevertheless, PlatformIO is a place where are located hundreds libs. This is the next issue why PlatformIO Library Manager operates with "LIBRARY_ID", not "LIBRARY_NAME". Library name can be changed when "someone" comes to me. However, LIBRARY_ID won't be changed.

**Comment by ivanseidel** [comment]
Got it!

Anyway, nice job at PlatformIO! If you need a hand, drop me an email: ivanseidel_at_gmail.com

**Comment by ivankravets** [comment]
Thanks! Follow us on Twitter [@PlatformIO_Org](https://twitter.com/PlatformIO_Org).

P.S: Will wait a feedback from you about @PlatformIO.

**Pull request merged**
